name: Stage the app

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')

    steps:
      - uses: actions/checkout@v4
      - name: Staging build
        run: echo "Staging build triggered!"
      # …your real build/test/deploy steps here
